### ISSUE TITLE
@" "@ for multiline string makes all following lines color syntax wrong

### ISSUE THREAD

**Issue by ksipple** [jugglingnutcase/language-powershell#43] opened 2015-08-12 00:46 UTC
when I am defining multiline strings the first @ makes all the following lines color look like it is in "quotes"
the second @ should cancel the first out

example:
$myString = @"
This is the first line
This the second line
This is the third line
"@

**Comment by jugglingnutcase** [comment] 2015-08-12 13:59
Thanks for this! i'll take a deeper look into this.

**Comment by radum** [comment] 2015-08-18 14:37
It's ok for me as far as I can see. Can you send a print screen @ksipple ?

**Comment by jugglingnutcase** [comment] 2015-08-18 15:13
Yeah, i'm not seeing this either. Using:

```powershell
$myString = @"
This is the first line
This the second line
This is the third line
"@

Write-Host Building web resources... -NoNewLine
npm install --quiet
```

i see the following:

![image](https://cloud.githubusercontent.com/assets/238079/9333901/0dc65074-459a-11e5-8fbb-1eecec60d3f1.png)

**Comment by ksipple** [comment] 2015-08-18 15:24
I guess it only happens when I do this:

$myString = @"
This is the first line
This the second line
This is the third line"@

Write-Host Building web resources... -NoNewLine
npm install --quiet

[image: Inline image 1]

**Comment by vors** [comment] 2015-08-18 16:39
It's by design: the end of here-string must be `"@` at the beginning of the line 

https://technet.microsoft.com/en-us/library/ee692792.aspx?f=255&MSPPError=-2147217396


We want to assign our string value to a variable named $x; that’s why we started things off with $x = followed by @", the syntax that represents the start of our here-string. (Which, we should add, needs to be on a line all by itself.) We then indicate the end of the here-string by typing **the construction "@, also on a line by itself**.

**Comment by jugglingnutcase** [comment] 2015-08-18 18:08
Thanks for the clarification, @vors. Closing since this is by design.

**Closed by jugglingnutcase** 2015-08-18 18:08 UTC
